# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress tests
        uses: cypress-io/github-action@v1
        with:
          start: "npm run start"
          wait-on: "http://localhost:3000"
          # let's see if the Test Runner handles url in the config
          # https://github.com/cypress-io/cypress/issues/5466
          config: baseUrl=http://localhost:3000
